apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guessgame
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: guessgame
    spec:
      containers:
      - name: guessgame
        image: sivarajanr/guessgame:6
        ports:
        - name: game-http
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: guessgame-service
  labels:
    app: guessgame-service
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 5000
      name: game-http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: guessgame