apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guessgame
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: guessgame
    spec:
      containers:
      - name: guessgame
        image: IMAGEPATH:TAG
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: guessgame-service
  labels:
    app: guessgame-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 5000
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: guessgame